import ImgOne from "../app/Image/ImgOne.jpeg";

import Codereviewcuate from '../app/Icons/Codereviewcuate.png';
import Marketingamico from '../app/Icons/Marketingamico.png';
import BusinessPlanamico from '../app/Icons/BusinessPlanamico.png';
import Developeractivitybro from '../app/Icons/Developeractivitybro.png';
import Lowcodedevelopmentamico from '../app/Icons/Lowcodedevelopmentamico.png';
import Visualdatabro from '../app/Icons/Visualdatabro.png';
import MobileMarketingbro from '../app/Icons/MobileMarketingbro.png';
import Robotfaceamico from '../app/Icons/Robotfaceamico.png';
import Handcodingpana from  '../app/Icons/Handcodingpana.png';
import JavaScriptframeworksbro from '../app/Icons/JavaScriptframeworksbro.png';
import Analyticsbro from '../app/Icons/Analyticsbro.png';
import Ambassadorbro from '../app/Icons/Ambassadorbro.png'
import Dataextractionrafiki from '../app/Icons/Dataextractionrafiki.png';
import Softwareengineerbro from  '../app/Icons/Softwareengineerbro.png';
import Codingworkshopamico from '../app/Icons/Codingworkshopamico.png';

const getjobs = [
    {
        id: 1,
        title: "Software Engineer",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Kenya",
        salary: "Ksh 100,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Develop interactive dashboards for data analysis",
        jobrequirementskills: "JavaScript, D3.js, React, Data Analysis",
        jobresponsibilities: "Design and implement data visualization solutions",
        contractTerm: "5 months",
    },
    {
        id: 2,
        title: "Affiliate Marketer",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Part Time",
        typeofsystem: "Hybrid",
        country: "Nigeria",
        salary: "₦150,000",
        cardImgIcon: Marketingamico,
        bgdetailspage: ImgOne,
        projectdescription: "Promote company products through affiliate channels",
        jobrequirementskills: "Marketing, Social Media, SEO, Content Creation",
        jobresponsibilities: "Generate leads and drive sales through affiliate links",
        contractTerm: "3 months",
    },
    {
        id: 3,
        title: "Data Scientist",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "On-site",
        country: "South Africa",
        salary: "R45,000",
        cardImgIcon: BusinessPlanamico,
        bgdetailspage: ImgOne,
        projectdescription: "Develop machine learning models for business insights",
        jobrequirementskills: "Python, TensorFlow, SQL, Statistics",
        jobresponsibilities: "Analyze large datasets and build predictive models",
        contractTerm: "12 months",
    },
    {
        id: 4,
        title: "Frontend Developer",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Egypt",
        salary: "EGP 25,000",
        cardImgIcon: Developeractivitybro,
        bgdetailspage: ImgOne,
        projectdescription: "Build responsive web applications",
        jobrequirementskills: "React, JavaScript, CSS, HTML",
        jobresponsibilities: "Implement user interfaces and ensure cross-browser compatibility",
        contractTerm: "6 months",
    },
    {
        id: 5,
        title: "Python Programmer",
        typeofcarees: "Programming",
        typeofworks: "Contract",
        typeofsystem: "Remote",
        country: "Morocco",
        salary: "MAD 20,000",
        cardImgIcon: Lowcodedevelopmentamico,
        bgdetailspage: ImgOne,
        projectdescription: "Backend development for financial applications",
        jobrequirementskills: "Python, Django, REST APIs, PostgreSQL",
        jobresponsibilities: "Develop and maintain backend services",
        contractTerm: "4 months",
    },
    {
        id: 6,
        title: "Data Visualization Specialist",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Ghana",
        salary: "GHS 8,000",
        cardImgIcon: Visualdatabro,
        bgdetailspage: ImgOne,
        projectdescription: "Create interactive reports for business intelligence",
        jobrequirementskills: "Tableau, Power BI, SQL, Data Analysis",
        jobresponsibilities: "Transform complex data into visual stories",
        contractTerm: "8 months",
    },
    {
        id: 7,
        title: "Digital Marketing Affiliate",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Part Time",
        typeofsystem: "Remote",
        country: "Tanzania",
        salary: "TZS 1,500,000",
        cardImgIcon: MobileMarketingbro,
        bgdetailspage: ImgOne,
        projectdescription: "Promote educational technology products",
        jobrequirementskills: "Digital Marketing, Content Creation, Analytics",
        jobresponsibilities: "Drive traffic and conversions through affiliate networks",
        contractTerm: "6 months",
    },
    {
        id: 8,
        title: "AI Research Engineer",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "On-site",
        country: "Algeria",
        salary: "DZD 300,000",
        cardImgIcon: Robotfaceamico,
        bgdetailspage: ImgOne,
        projectdescription: "Research and develop NLP solutions",
        jobrequirementskills: "Python, PyTorch, NLP, Machine Learning",
        jobresponsibilities: "Implement and optimize AI algorithms",
        contractTerm: "12 months",
    },
    {
        id: 9,
        title: "Full Stack Developer",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Ethiopia",
        salary: "ETB 50,000",
        cardImgIcon: Handcodingpana,
        bgdetailspage: ImgOne,
        projectdescription: "Build end-to-end web applications",
        jobrequirementskills: "JavaScript, Node.js, React, MongoDB",
        jobresponsibilities: "Develop both frontend and backend components",
        contractTerm: "9 months",
    },
    {
        id: 10,
        title: "Java Developer",
        typeofcarees: "Programming",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Uganda",
        salary: "UGX 6,000,000",
        cardImgIcon: JavaScriptframeworksbro,
        bgdetailspage: ImgOne,
        projectdescription: "Enterprise application development",
        jobrequirementskills: "Java, Spring Boot, Microservices, SQL",
        jobresponsibilities: "Design and implement scalable backend services",
        contractTerm: "12 months",
    },
    {
        id: 11,
        title: "BI Analyst",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "On-site",
        country: "Angola",
        salary: "AOA 400,000",
        cardImgIcon: Analyticsbro,
        bgdetailspage: ImgOne,
        projectdescription: "Create business intelligence dashboards",
        jobrequirementskills: "Power BI, SQL, Data Modeling, Excel",
        jobresponsibilities: "Analyze business metrics and present insights",
        contractTerm: "6 months",
    },
    {
        id: 12,
        title: "Affiliate Manager",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Senegal",
        salary: "XOF 350,000",
        cardImgIcon: Ambassadorbro,
        bgdetailspage: ImgOne,
        projectdescription: "Manage affiliate marketing program",
        jobrequirementskills: "Affiliate Marketing, Relationship Management, Analytics",
        jobresponsibilities: "Recruit and manage affiliate partners",
        contractTerm: "12 months",
    },
    {
        id: 13,
        title: "Machine Learning Engineer",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Tunisia",
        salary: "TND 4,500",
        cardImgIcon: Dataextractionrafiki,
        bgdetailspage: ImgOne,
        projectdescription: "Develop recommendation systems",
        jobrequirementskills: "Python, Scikit-learn, TensorFlow, Data Pipelines",
        jobresponsibilities: "Build and deploy ML models",
        contractTerm: "10 months",
    },
    {
        id: 14,
        title: "DevOps Engineer",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Cameroon",
        salary: "XAF 500,000",
        cardImgIcon: Softwareengineerbro,
        bgdetailspage: ImgOne,
        projectdescription: "Implement CI/CD pipelines",
        jobrequirementskills: "AWS, Docker, Kubernetes, Terraform",
        jobresponsibilities: "Automate deployment processes",
        contractTerm: "12 months",
    },
    {
        id: 15,
        title: "C# Developer",
        typeofcarees: "Programming",
        typeofworks: "Contract",
        typeofsystem: "On-site",
        country: "Zimbabwe",
        salary: "USD 2,500",
        cardImgIcon: Codingworkshopamico,
        bgdetailspage: ImgOne,
        projectdescription: "Desktop application development",
        jobrequirementskills: "C#, .NET, WPF, SQL Server",
        jobresponsibilities: "Develop and maintain business applications",
        contractTerm: "6 months",
    },
    {
        id: 16,
        title: "Data Visualization Developer",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Mozambique",
        salary: "MZN 80,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Create interactive data visualizations for reports",
        jobrequirementskills: "JavaScript, D3.js, React, Data Analysis",
        jobresponsibilities: "Design and implement visualization solutions",
        contractTerm: "8 months",
    },
    {
        id: 17,
        title: "Affiliate Marketing Specialist",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Part Time",
        typeofsystem: "Remote",
        country: "Madagascar",
        salary: "MGA 1,200,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Promote travel and tourism products",
        jobrequirementskills: "Digital Marketing, Social Media, Analytics",
        jobresponsibilities: "Drive sales through affiliate networks",
        contractTerm: "4 months",
    },
    {
        id: 18,
        title: "Data Engineer",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Côte d'Ivoire",
        salary: "XOF 450,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Build and maintain data pipelines",
        jobrequirementskills: "Python, SQL, Airflow, ETL",
        jobresponsibilities: "Design and optimize data infrastructure",
        contractTerm: "12 months",
    },
    {
        id: 19,
        title: "Mobile Developer",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Zambia",
        salary: "ZMW 25,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Cross-platform mobile app development",
        jobrequirementskills: "Flutter, Dart, Firebase, REST APIs",
        jobresponsibilities: "Build and maintain mobile applications",
        contractTerm: "9 months",
    },
    {
        id: 20,
        title: "PHP Developer",
        typeofcarees: "Programming",
        typeofworks: "Contract",
        typeofsystem: "Remote",
        country: "Namibia",
        salary: "NAD 35,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "E-commerce platform development",
        jobrequirementskills: "PHP, Laravel, MySQL, JavaScript",
        jobresponsibilities: "Develop and maintain web applications",
        contractTerm: "5 months",
    },
    {
        id: 21,
        title: "Tableau Developer",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "On-site",
        country: "Botswana",
        salary: "BWP 15,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Create business intelligence dashboards",
        jobrequirementskills: "Tableau, SQL, Data Analysis, Visualization",
        jobresponsibilities: "Develop interactive reports for stakeholders",
        contractTerm: "6 months",
    },
    {
        id: 22,
        title: "Affiliate Content Creator",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Part Time",
        typeofsystem: "Remote",
        country: "Rwanda",
        salary: "RWF 1,000,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Create content for affiliate marketing campaigns",
        jobrequirementskills: "Content Writing, SEO, Social Media",
        jobresponsibilities: "Produce engaging content to drive conversions",
        contractTerm: "3 months",
    },
    {
        id: 23,
        title: "Computer Vision Engineer",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Libya",
        salary: "LYD 3,500",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Develop image recognition systems",
        jobrequirementskills: "Python, OpenCV, TensorFlow, Deep Learning",
        jobresponsibilities: "Implement computer vision algorithms",
        contractTerm: "12 months",
    },
    {
        id: 24,
        title: "Backend Developer",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Sudan",
        salary: "SDG 250,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "API development for mobile applications",
        jobrequirementskills: "Node.js, Express, MongoDB, REST APIs",
        jobresponsibilities: "Design and implement backend services",
        contractTerm: "8 months",
    },
    {
        id: 25,
        title: "Ruby on Rails Developer",
        typeofcarees: "Programming",
        typeofworks: "Contract",
        typeofsystem: "Remote",
        country: "Mauritius",
        salary: "MUR 60,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Web application development",
        jobrequirementskills: "Ruby, Rails, PostgreSQL, JavaScript",
        jobresponsibilities: "Build and maintain web applications",
        contractTerm: "6 months",
    },
    {
        id: 26,
        title: "Data Visualization Analyst",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Seychelles",
        salary: "SCR 30,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Create visual reports for tourism statistics",
        jobrequirementskills: "Power BI, Excel, Data Analysis, Storytelling",
        jobresponsibilities: "Transform data into actionable insights",
        contractTerm: "7 months",
    },
    {
        id: 27,
        title: "Affiliate Marketing Coordinator",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Benin",
        salary: "XOF 300,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Coordinate affiliate marketing campaigns",
        jobrequirementskills: "Marketing, Communication, Analytics",
        jobresponsibilities: "Manage relationships with affiliate partners",
        contractTerm: "12 months",
    },
    {
        id: 28,
        title: "NLP Specialist",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "On-site",
        country: "Burkina Faso",
        salary: "XOF 400,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Develop natural language processing solutions",
        jobrequirementskills: "Python, NLP, Machine Learning, Text Mining",
        jobresponsibilities: "Implement language models and text analysis tools",
        contractTerm: "10 months",
    },
    {
        id: 29,
        title: "Game Developer",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Malawi",
        salary: "MWK 500,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Mobile game development",
        jobrequirementskills: "Unity, C#, Game Design, 3D Modeling",
        jobresponsibilities: "Develop and optimize mobile games",
        contractTerm: "9 months",
    },
    {
        id: 30,
        title: "Go Developer",
        typeofcarees: "Programming",
        typeofworks: "Contract",
        typeofsystem: "Remote",
        country: "Niger",
        salary: "XOF 350,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Microservices development",
        jobrequirementskills: "Go, Docker, Kubernetes, REST APIs",
        jobresponsibilities: "Build scalable backend services",
        contractTerm: "5 months",
    },
    {
        id: 31,
        title: "GIS Visualization Specialist",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "On-site",
        country: "Chad",
        salary: "XAF 400,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Create geographic data visualizations",
        jobrequirementskills: "GIS, Python, QGIS, Spatial Analysis",
        jobresponsibilities: "Develop maps and spatial data visualizations",
        contractTerm: "6 months",
    },
    {
        id: 32,
        title: "Affiliate Marketing Consultant",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Part Time",
        typeofsystem: "Remote",
        country: "Somalia",
        salary: "USD 1,200",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Provide affiliate marketing strategy",
        jobrequirementskills: "Digital Marketing, Strategy, Analytics",
        jobresponsibilities: "Advise clients on affiliate marketing programs",
        contractTerm: "3 months",
    },
    {
        id: 33,
        title: "AI Product Manager",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Liberia",
        salary: "USD 3,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Manage AI product development",
        jobrequirementskills: "Product Management, AI, Agile, Stakeholder Management",
        jobresponsibilities: "Oversee AI product lifecycle",
        contractTerm: "12 months",
    },
    {
        id: 34,
        title: "iOS Developer",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Guinea",
        salary: "GNF 30,000,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Native iOS app development",
        jobrequirementskills: "Swift, UIKit, Core Data, REST APIs",
        jobresponsibilities: "Build and maintain iOS applications",
        contractTerm: "8 months",
    },
    {
        id: 35,
        title: "Rust Developer",
        typeofcarees: "Programming",
        typeofworks: "Contract",
        typeofsystem: "Remote",
        country: "Mali",
        salary: "XOF 400,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Blockchain development",
        jobrequirementskills: "Rust, Blockchain, Cryptography, Distributed Systems",
        jobresponsibilities: "Develop blockchain protocols and applications",
        contractTerm: "6 months",
    },
    {
        id: 36,
        title: "Healthcare Data Visualizer",
        typeofcarees: "Data Visualization",
        typeofworks: "Full Time",
        typeofsystem: "On-site",
        country: "Eswatini",
        salary: "SZL 20,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Visualize healthcare metrics and trends",
        jobrequirementskills: "Tableau, Healthcare Data, Statistics, Visualization",
        jobresponsibilities: "Create dashboards for healthcare analytics",
        contractTerm: "7 months",
    },
    {
        id: 37,
        title: "Affiliate Marketing Analyst",
        typeofcarees: "Affiliate Marketer",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Lesotho",
        salary: "LSL 15,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Analyze affiliate marketing performance",
        jobrequirementskills: "Analytics, Excel, Digital Marketing, Reporting",
        jobresponsibilities: "Track and optimize affiliate campaigns",
        contractTerm: "12 months",
    },
    {
        id: 38,
        title: "AI Ethics Specialist",
        typeofcarees: "Data/AI",
        typeofworks: "Full Time",
        typeofsystem: "Hybrid",
        country: "Congo",
        salary: "XAF 500,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Ensure ethical AI development practices",
        jobrequirementskills: "AI Ethics, Policy, Machine Learning, Research",
        jobresponsibilities: "Develop guidelines for responsible AI",
        contractTerm: "10 months",
    },
    {
        id: 39,
        title: "Cloud Architect",
        typeofcarees: "Development",
        typeofworks: "Full Time",
        typeofsystem: "Remote",
        country: "Gabon",
        salary: "XAF 600,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Design cloud infrastructure solutions",
        jobrequirementskills: "AWS, Azure, Cloud Security, Infrastructure",
        jobresponsibilities: "Architect scalable cloud systems",
        contractTerm: "12 months",
    },
    {
        id: 40,
        title: "Kotlin Developer",
        typeofcarees: "Programming",
        typeofworks: "Contract",
        typeofsystem: "Remote",
        country: "Togo",
        salary: "XOF 350,000",
        cardImgIcon: Codereviewcuate,
        bgdetailspage: ImgOne,
        projectdescription: "Android application development",
        jobrequirementskills: "Kotlin, Android SDK, Jetpack, REST APIs",
        jobresponsibilities: "Build and maintain Android applications",
        contractTerm: "5 months",
    }
];

export default getjobs;